PLU_DATA = {
    "93073": {
        "zone": "U",
        "zone_libelle": "Urbaine",
        "cos": 0.50,
        "hauteur_max": 12.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 375.0,
        "niveaux_max": 2,
    },
    "93005": {
        "zone": "U",
        "zone_libelle": "Urbaine",
        "cos": 0.60,
        "hauteur_max": 15.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 450.0,
        "niveaux_max": 2,
    },
    "93071": {
        "zone": "U/AU",
        "zone_libelle": "Urbaine/AU",
        "cos": 0.50,
        "hauteur_max": 10.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 375.0,
        "niveaux_max": 2,
    },
    "93046": {
        "zone": "U",
        "zone_libelle": "Urbaine",
        "cos": 0.50,
        "hauteur_max": 12.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 375.0,
        "niveaux_max": 2,
    },
    "93007": {
        "zone": "U",
        "zone_libelle": "Urbaine",
        "cos": 0.70,
        "hauteur_max": 15.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 525.0,
        "niveaux_max": 2,
    },
    "93078": {
        "zone": "U",
        "zone_libelle": "Urbaine",
        "cos": 0.50,
        "hauteur_max": 10.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 375.0,
        "niveaux_max": 2,
    },
    "95277": {
        "zone": "AU/U",
        "zone_libelle": "AU/Urbaine",
        "cos": 0.40,
        "hauteur_max": 8.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 300.0,
        "niveaux_max": 2,
    },
    "95527": {
        "zone": "AU",
        "zone_libelle": "AU",
        "cos": 0.30,
        "hauteur_max": 8.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 225.0,
        "niveaux_max": 1,
    },
    "77294": {
        "zone": "U",
        "zone_libelle": "Urbaine",
        "cos": 0.50,
        "hauteur_max": 12.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 375.0,
        "niveaux_max": 2,
    },
    "77508": {
        "zone": "U",
        "zone_libelle": "Urbaine",
        "cos": 0.60,
        "hauteur_max": 12.0,
        "recul_voie": 3.0,
        "recul_lateral": 1.5,
        "recul_fond": 3.0,
        "emprise_max": 450.0,
        "niveaux_max": 2,
    },
}


def get_plu(commune_code: str) -> dict:
    return PLU_DATA.get(commune_code, PLU_DATA["93073"])
